language: r
cache: packages
warnings_are_errors: false
r_check_arg: --no-manual
script: R CMD BATCH annotate_domains.R && cat annotate_domains.Rout && wc -l $(ls -1 Glycodomain-*[0-9]*.tsv)
after_success:
- test ! -z ${TRAVIS_TAG} && curr=$(ls -1 Glycodomain-*[0-9]*.tsv) && cp $curr "Glycodomain-${TRAVIS_TAG}${curr#Glycodomain}"
  && cp $curr "Glycodomain-latest${curr#Glycodomain}" && cp Glycodomain-latest*.tsv
  Glycodomain-latest-InterPro-latest-class.tsv && rm $curr && mkdir dist && cp Glycodomain-*.tsv dist
before_deploy:
- export RELEASE_FILES=$(ls Glycodomain-*.tsv)
- echo "Deploying $RELEASE_FILES"
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
after_deploy:
- interpro=$(ls -1 Glycodomain-*[0-9]*.tsv | sed -e 's/-class\.tsv//' -e 's/.*Interpro-//'); aws s3api put-object --bucket node-lambda --key 'glycodomain/Glycodomain-latest-InterPro-latest-class.tsv' --metadata "version=${TRAVIS_TAG},interpro=${interpro}"
deploy:
  provider: s3
  local-dir: dist
  skip_cleanup: true
  upload-dir: glycodomain
  bucket: node-lambda
  on:
    tags: true
  access_key_id: AKIAIFJ7QRANDJVX6PIA
  secret_access_key:
    secure: krZCwo/jP+v5nRjcFN7mpQOF8vYNcSyeccMYnpanq3cXRZdawCyypsfkdLB2n7zSaQxrDvsHcZEZhz32hIKvO7C7w9acCpjkarSsbnrDJtU1m/44XEl4hv6QEyNeAlQk/QFlrQTayVipxD5WGDSPCZi5STCH8g7beaxc1FFf03b9qDu2EbFsbQfHvREUOx5SUu9axbifMrT9oacaK0ACzagLeo2DLP9fYaqHe6G49fXNM9iB+aRHzx9lYyBvUXhzBJLjI0IQC2+DjSu3EsR3DdB+xyXbWxo7NjV0MKFK15JHAYRF2Psp5xZ6TIw6FptajnjCxfNeHy4EJK+yHM78jNdHZmHrdAc7VVPvYeraYLCpV8psnAWLXJD8p0Uu0XlK6Z0Tm+99EbljuPn03PXxwfzyUNnIkrKotaeKcByJ+H7xw+Xyc0vNorofGdGfX/yV9n9Ve+lu1Xre/9umHXu2y69BX45+P3VKU67QMTDCHm4XRbjmAX6T/0fEQtdYtjv9J6dWPlhQ30uUOu2XScYE5wdrRXe8f3rXFCWlvfHzOEBwyRNWRuLonUVYpgdt/Ss/LnESFc/SDkQPObItwRzb7ILAnK0oq2YSpLZJ3F0+iiMcBGN0aRtNw3ubAorovSsWMwoBvRlduaowN8x4aD2hhcDWITpfvSRc7s+KxY9YV5o=
env:
  global:
  - secure: Owy38YHMDFf24laThZ60/ReIKxxR5C0Qa2UACBNTxFAfEJgGWDZtJw48s5Zn+LHYEDKqn4ST9Lp1TTZuiUu+8ltTEyLrOlq8yfvgu171F0pn5u/edU00fGeyDOinmdeRZJDT+Ps/v7/68+Asr0KnZmsyUIGVx1YBT2IqMhI8p+PlILVVK1VXLN/RSyPvKKF4Ido/ZWL864I4RM1/jHy5apr7dULcs82UyNOFZ8ovjmES0HbMgCKy4WtGQY8qJ8uVs+xJBM1N9AoblYpJYhasJs/LtB0lSxrNd7Akp6jMRfFa+urrdXwVxn2gc+iEwO4SPwHD9CCKtaFMuAdEmuUjxnz1IFNrtHi6UVHRjexkeKKzBrtjn4g2Q3JWpK9gaTHTe4NjXtc0Dy7u+X20X6G7orKXzs13ScU6hp3SWqIHGGOanYs7DibuDX/KJP0X6qtVGzjhzPRxcx3fb5yApHZh/HkteM1ibJ5erPAbdPESK8eEl6AWXyofSN3nSEm8EDCcjS1gduD/VsU4+HEKRdd51aBzo4sgIX2KDTrz2iDeAEWKXN1D1IV5cla/W8GalrRjgq0Xnr5eUM2TbuK+EA4o2UKrXgYzsD03DhQkHCiyuaim2x79Fr2vyaMPV9WsAL0sLDShs/Zbhxd9U5mb9OK/vAfWbZMyxBEZDW958Z27VMg=
  - secure: vaSSEA9JsUF5ZWbdWoDPl64sOkBfAxKmZ7a4fwtArpxsCUlhLcDXymBQ4fZBnM/bldMVM2OjRn5jQrnuSOe/xEjd7Di+dHMRROuoQtiOH+ABVPke016oECoshlC5e465GOc7J2yz/ltNIpShTgLtV0htNd5k0AaQk5bewEIbas3tKZti69BkFvAGONJila1QjI6D9ZLBiJVQD2uUgyG5a5IMeyNVELYyQzLQorSvFe2DOvHJ18iTlWqqX9OeXTRgJswPKi8F3ZBrarrvZvvj8PJ2n1h+wk3vq3cxE39tgT2N9RAKo7Ci5S10862/AVxK2KjCUb0XFnW1Kj1qsfFHf0XGFfiXy/e7QbbedZee04BA4d5c/QTU8f2WUrjjIUbBA2KEyvtwSsjRD1upUUk25P2YjNwHES3xriH7NX43qwUMKu8tPOBETZGlu2qiXk9j2Wpy5m5sTtLVcxMam2RYa6d2DDNEShvYXjyPaeqRDYpRYQ2WToxhXW6DPux5CtDlhM+DdzvNue7zO+1PUWKvwGajOvR+va5diV6Xc6pxvDL0NT49x3AaGI4wtOyfLRQMCdx2vQ/IbOOTKglzxYPCeZYs+w2SKAsFYXqJOCjVpN5jHiqDgyaB+fKCIZFdWK5wGlr7qPKULWgttsdjfwIcJj2dCeSaVUrVcREu+4zkWYE=
