language: r
cache: packages
warnings_are_errors: false
r_check_arg: --no-manual
script: R CMD BATCH annotate_domains.R && cat annotate_domains.Rout && wc -l $(ls -1 Glycodomain-*[0-9]*.tsv)
after_success:
- test ! -z ${TRAVIS_TAG} && curr=$(ls -1 Glycodomain-*[0-9]*.tsv) && cp $curr "Glycodomain-${TRAVIS_TAG}${curr#Glycodomain}"
  && cp $curr "Glycodomain-latest${curr#Glycodomain}" && cp Glycodomain-latest*.tsv
  Glycodomain-latest-InterPro-latest-class.tsv && rm $curr && mkdir dist && cp Glycodomain-*.tsv dist
before_deploy:
- export RELEASE_FILES=$(ls Glycodomain-*.tsv)
- echo "Deploying $RELEASE_FILES"
deploy:
  provider: s3
  local-dir: dist
  skip_cleanup: true
  upload-dir: glycodomain
  bucket: node-lambda
  on:
    tags: true
  access_key_id: AKIAJ2VL3UT6LDQRRRAA
  secret_access_key:
    secure: GLRl1tnDXXDrFUQsPJ3VudZNAQMRImHcwWfBOhGZhUrYzVW+SrvbU8tPlSdC6So+k8OFP5DysuxRx3niDq63LZaBAzAQI6cZmjFmMYBwahML2CAGexMB3IVuwRx7YaTeXseqbmW1Mlcp8oHEOx6r99Fay2PrTxyb9A/fgwTysr01Xmbb4c4p7ZfR41ryi2SnqZ6HvsCXAtdWj14nuBCCcs9LKo9TySIoW+7KB62t/5+2g55DDlqSERlcqOsP9E6HwF///LDLF6Nay9r/8ZrWaoxyt878K7hdkONUJFAo55U/2BUgczgvtMBbWmgNqFyQxSszZmj2CPFd5tU2rXiBrf50Jj5C08MTMiLp/K3RaLWTP4x0iKih2mLTZ+A9lwXu32fCUyPouM+u1b8fJdJQ8v9kuCSSVYtndmjPyUq7SFr21RGPdlPYFM8ORgrDjgXTd9G+84bM4TH+WsufseV7WbSg8WipfKomcbcC1zI01dpdFCTOWivkchLMf+n4qdvsLRqapdD2hNXWLDyoYWLwxHq31Qfu9SvESs+RYtxfVDz8mUjpmA+8Nll/uARyQODI4hqXQiAz9/cahQP3xQRK0jqJw3gZIeusXxx3Aq6O1Ny7/DaqZOakMAgiQ/o+fPpLyR0UGK5Y+/45jPs/ZAe11nt1qbe2g8wAC3VwFC0x0Vs=
